[package]
name = "pyo3-ml"
version = "0.1.0"
authors = ["Pratheek Hegde <hegdep@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.pyo3]
version = "0.15.1"
features = ["auto-initialize"]
